### ISSUE TITLE
Redesign website

### ISSUE THREAD

**Issue by fvcproductions** [fvcproductions/apprenticeships.me#22]
Should look something like the image below (thank you @benjaminmodayil for the lovely design!) but should be using an existing CSS framework that will be easy to build upon. 

Bulma - https://bulma.io

![49157936-016fa680-f2ef-11e8-8f20-9dd8fbfda33e](https://user-images.githubusercontent.com/4284691/50177681-a0753600-02d0-11e9-8c1b-63e9f9d116e4.png)

---

> ✅️ By submitting this issue, I have verified the following

* [x] Checked to see if the issue has already been discussed before 🤔️
* [x] If proposing new content to be added, made sure enough details were provided 🔍️

**Comment by benjaminmodayil** [comment]
Hi @fvcproductions I've updated the design a little. I moved away from the strict sidebar menu. I felt that if we detached it, the menu would feel like a single-page site menu. I think this communicates a little bit more clearly that each link scrolls to a different section on the page. You'll notice the menu in each section. It's just like that to communicate that when you scroll it remains fixed to the screen.

I've also added the other sections you mentioned in your previous message.

Things to note: 
1. Apprenticeships.me is there as the temporary title as I believe the actual site title wasn't decided yet.
2. What should I place in the footer/bottom of the page. I guess there needs to be a copyright or something? I'm not sure how it works for a project like this.
3. I'm looking at different methods of displaying the "cards" within the search functionality. I feel like the individual cards are a little dense and I'm thinking of changing them up a little to reveal more information on click/hover/etc instead of all at once (might just work on this in code).
4. Related Resources section feels "off" and this section could get rough once more items are added to the repository.

I can work on building the site tomorrow if you think the updated design look good. I saw you mention bulma, would you be opposed to using something like Tailwind instead (https://tailwindcss.com)? I'm really down for either honestly. I'm honestly just a Tailwind fanboy 😆.

![desktop hd copy 3](https://user-images.githubusercontent.com/12306850/50227441-bc7de380-0373-11e9-861d-2c0610af90c8.png)

**Comment by fvcproductions** [comment]
@benjaminmodayil Love the design again! 💯 

Here are my thoughts:

1. Repo title can stay as `apprenticeships` and website title and domain can be `Apprenticeships.me` like in your design.
2. We can just have a simple "Copyright ©️ {CurrentYear}" for the footer. 
3. For now, I think we have minimal information so that it looks fine with all the info displayed within the card but down the line, to scale, we might want to have the card direct to a page with more rich info, images, etc. with the link - similar to how Course Report does it. https://www.coursereport.com/schools/fullstack-academy
4. The related resources looks good as is and actually two or three of those links belong as their own cards now.

## Other Thoughts

5. I like the new design structure - I do agree that it makes it more obvious there are distinct sections. For the cards, we can perhaps little buttons in the corner to make the categories/roles more obvious like shown here: https://tailwindcss.com/docs/examples/cards
6. Tailwind is totally fine - let's do it! I've looked into before - just never tried it. I fangirl over Bulma instead (LOL).
7. What do you think will be your approach for the GitHub contributors section?
8. I imagine the "Contribute" button would direct users to the new GitHub issue link at which point someone could create a PR for it or would it redirect the user to the contributing guidelines? Or maybe something else?

**Comment by benjaminmodayil** [comment]
@fvcproductions Everything you said sounds good!

In reply to specific points:
3. I like the eventual direction with the new "rich info" page. But I'll keep it in the card format for now.
4. Can you elaborate on "two or three of those links belong as their own cards now"? I'm a little confused what you mean by this.
7. Are you referring on my plan for pulling in contributor data? My plan was to hit the Github API and pull in the avatar/link data. I did a quick test awhile back and I believe all the data needed is there.
8. Hmmm. This is a good question. I feel like it would open to a new issue, but there should be a link right before the button to the contributing guidelines. 

I'll take some time tomorrow and work on the site. Thanks!

**Comment by fvcproductions** [comment]
@benjaminmodayil 

3. Sounds good! 👍 
4. The links that form the resources section - 2 of those need to be removed and added in as their own cards (Thoughtbot, Treehouse)
7. Yep - that sounds good! Here is a resource I found for showing contributors: https://github.com/kentcdodds/all-contributors
8. Maybe the Contributing guidelines can just be properly showcased in the new issue link because we would be using a custom issue template.

**Comment by benjaminmodayil** [comment]
Just updating you, I'll submit a PR either tonight or tomorrow. Last week and half have been busy with the holidays and all. There is a branch up, but just a little bit more to do on it. I'm also trying to add all the "role" tags in the front matter for each listing so we have access to whether it's a front-end or etc role on the cards.
