### ISSUE TITLE
Remove empty apprentice from page 4

### ISSUE THREAD

**Issue by gkunwar** [fvcproductions/apprenticeships.me#62]
In page 4 (https://apprenticeships.me/?page=4) there is a empty apprentice.

---

> ✅️ By submitting this issue, I have verified the following

- [x] Checked to see if the issue has already been discussed before 🤔️
- [X] If proposing new content to be added, made sure enough details were provided 🔍️

**Comment by benjaminmodayil** [comment]
Removed extra page. There was a `null` value in Algolia for one of the apprenticeships. Seems to have been caused by deleting one of the existing ones from a previous issue and Algolia adjusting IDs in a weird way.

I'm thinking of a way to do a check before Algolia gives us a query, but I'm not sure of how to do it at the moment with the instantsearch API.
